import { Education } from "./Education";

export const EducationLists: Education[] = [
  {
    school: "Johns Hopkins University",
    degree: "Master of Science in Engineering",
    major: "Computer Science",
    start_date: "09/2020",
    end_date: "12/2022",
    place: "Baltimore, MD, USA",
    link: "https://www.jhu.edu/",
    bg_img: "../../../assets/jhu_logo.png",
    width_logo: 165,
    height_logo: 105,
  },
  {
    school: "Shanghai Jiao Tong University",
    degree: "Bachelor of Science",
    major: "Electrical and Computer Engineering",
    start_date: "09/2016",
    end_date: "08/2020",
    place: "Shanghai, China",
    link: "https://www.sjtu.edu.cn/",
    bg_img: "../../../assets/sjtu_logo.png",
    width_logo: 75,
    height_logo: 75,
  },
  {
    school: "The University of Hong Kong",
    major: "Computer Science",
    exchange: "Undergraduate Student Exchange Program",
    start_date: "09/2019",
    end_date: "12/2019",
    place: "Hong Kong SAR",
    link: "https://www.hku.hk/",
    bg_img: "../../../assets/hku_logo.png",
    width_logo: 198,
    height_logo: 132,
  },
]
